spring.application.name=docker-spring-boot-jpa
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysqldb:3307/testdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.platform=mysql
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
